FEAT : ODYA-64 팔로우 생성/삭제, 팔로워/팔로잉 수 조회, 팔로잉/팔로워 무한스크롤 조회
weIT-1st/Odya-android pull request #17
Opened 2023-07-05 17:21 UTC by LeEjoNgmIn1

### 개요
1. 팔로우 생성
2. 팔로우 삭제
3. 팔로워/팔로잉 수 조회
4. 팔로잉 무한스크롤 조회
5. 팔로워 무한스크롤 조히

### 변경사항

### 관련 지라 및 위키 링크
https://weit.atlassian.net/jira/software/c/projects/ODYA/boards/1?modal=detail&selectedIssue=ODYA-64

### 리뷰어에게 하고 싶은 말
확인해주세요

2023-07-06 00:36 UTC, overthename approved these changes
수고하셨습니다 굿굿

2023-07-06 00:36 UTC, overthename commented on data/src/main/java/com/weit/data/service/FollowService.kt
> +    @GET("/api/v1/follows/1/counts")
주소에 userId부분 {} 감싸줘야 할 것 같아용

2023-07-06 00:36 UTC, overthename commented on data/src/main/java/com/weit/data/service/FollowService.kt
> +    @GET("/api/v1/follows/1/followings?page=1&size=1&sortType=OLDEST")
주소 부분 확인해주세용

2023-07-06 01:13 UTC, minseonglove requested changes
안대안대

2023-07-06 01:13 UTC, minseonglove commented on data/src/main/java/com/weit/data/service/FollowService.kt
> +    )
FormUrlEncoded는 Body에선 사용안해요 빼주면댑니다

2023-07-06 01:13 UTC, minseonglove commented on data/src/main/java/com/weit/data/service/FollowService.kt
> +    )
body 객체는 moshi를 통해 json으로 변환될 수 있어야 합니다.
즉, data 모듈에 있는 model만 넣을 수 있어요

2023-07-06 01:13 UTC, minseonglove commented on data/src/main/java/com/weit/data/repository/follow/FollowRepositoryImpl.kt
> +    }
에러 케이스를 보면서 사전에 막을 수 있는건 막아주면 좋아요
ex) 유저 id가 음수인 경우

2023-07-06 01:13 UTC, minseonglove commented on data/src/main/java/com/weit/data/service/FollowService.kt
> +}
Path인데 Path가 옵소요

2023-07-06 01:13 UTC, minseonglove commented on data/src/main/java/com/weit/data/service/FollowService.kt
> +}
api 문서에 나와 있는 url은 요청 예시고 follwers 뒤에 나오는 것들은 Query어노테이션을 통해 알아서 들어가는 내용이니 빼주면 됩니다.

2023-07-06 01:13 UTC, minseonglove commented on data/src/main/java/com/weit/data/service/FollowService.kt
> +}
문서에는 셋다 nullable이긴한데.. api 문서에 들어가지 않으면 default값을 알 수 없기 때문에 그냥 non-null로 하는 것도 괜찮아보여요

2023-07-08 07:59 UTC, minseonglove approved these changes
ㅋㅋ uri 오타만 수정하고 머지해주세요 고생했어요

2023-07-08 07:59 UTC, minseonglove commented on data/src/main/java/com/weit/data/service/FollowService.kt
> +    @GET("/api/v1/follows/{userId}}/followers")
이런 엄청난 오타가

2023-07-10 07:06 UTC, merged