FEAT : ODYA-33 Google Place 검색
weIT-1st/Odya-android pull request #7
Opened 2023-06-16 16:10 UTC by overthename

### 개요
* Google Place 검색
### 변경사항
1. 장소를 검색하면 자동 장소 목록을 제공합니다.
<img src="https://github.com/weIT-1st/Odya-android/assets/80188940/447f5245-4a3d-4427-95a3-ea207a6419eb"  width="200" height="400"/>

<br>

2. 장소 목록에서 장소를 클릭시 좌표값을 이용해 구글맵에 기본마커로 장소가 표시됩니다.
<img src="https://github.com/weIT-1st/Odya-android/assets/80188940/4e9b1480-3904-4730-8915-557170172dc7"  width="200" height="400"/>

### 관련 지라 및 위키 링크
[Place api 공식문서](https://developers.google.com/maps/documentation/places/android-sdk/autocomplete?hl=ko)
[ODYA-33](https://weit.atlassian.net/jira/software/c/projects/ODYA/boards/1?modal=detail&selectedIssue=ODYA-33)

### 리뷰어에게 하고 싶은 말
1. place 정보
Place api를 사용하여 place를 검색했을 때 가져오는 결과값을 나타내기 위한 데이터 클래스가 많습니다.
그 중 AddressType enum class안에 값들이 다 필요한가... 고민입니다. (AddressType클래스참조)
place api에서 제공하는 타입 전부인 것 같습니다

2. 검색 기능
검색할 시 리사이클러뷰가 나타나고 검색 목록 중에 하나를 선택시 리사이클러뷰가 사라지는 방법을 사용했는데 더 보기 좋은 방법이 있는지...

3. 현재는 검색어 목록을 선택시 좌표값만 받아와서 구글맵에 기본마커를 띄우는 식으로 구성하였습니다. 좌표 외의 다른 상세 정보를 받아올 수 있습니다.

2023-06-17 03:23 UTC, minseonglove requested changes
MapFragment에서 너무 많은 일을 하고있어요
지도 api 자체는 화면에 떠야하니까 어쩔 수 없다해도 Place Api는 충분히 Data모듈로 빼도 되보이네요 Place Api의 각 기능을 UseCase로 만들고 ViewModel이 그 UseCase를 사용해서 Fragment에 데이터를 전달하는 방식으로 개선해봅씨다

2023-06-17 03:23 UTC, minseonglove commented on presentation/build.gradle
> +    implementation 'com.android.volley:volley:1.2.1'
volley는 꼭 필요한가요?

2023-06-17 03:23 UTC, minseonglove commented on presentation/build.gradle
> +    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.6.1'
livedata는 안쓸거에용

2023-06-17 03:23 UTC, minseonglove commented on presentation/build.gradle
> +    implementation 'de.hdodenhof:circleimageview:3.1.0'
circleimageview도 쓰지 않겠읍니다

2023-06-17 03:23 UTC, minseonglove commented on presentation/src/main/java/com/weit/presentation/model/map/Bounds.kt
> +}
이 녀석은 data class로 해도 괜찮겠네요

2023-06-17 03:23 UTC, minseonglove commented on presentation/src/main/java/com/weit/presentation/model/map/GeocodingResult.kt
> +}
혹시 예제가 자바코드였나요

2023-06-17 03:23 UTC, minseonglove commented on presentation/src/main/java/com/weit/presentation/ui/map/MapFragment.kt
> +    private lateinit var recyclerView: RecyclerView
view를 필드변수로 만든 이유가 있나요?

2023-06-17 03:23 UTC, minseonglove commented on presentation/src/main/java/com/weit/presentation/ui/map/MapFragment.kt
> +        }
혹시 place initialize에 들어가는 context는 application context도 가능한가요?

2023-06-17 03:23 UTC, minseonglove commented on presentation/src/main/java/com/weit/presentation/ui/map/MapFragment.kt
> +                handler.postDelayed({ getPlacePredictions(newText) }, 300)
handler를 쓰고있네요 안쓰면 어떻게 되나요?

2023-06-19 03:35 UTC, minseonglove reviewed
죠습니다 리뷰 사항과 별개로 코드 정리를 위해 ktlint 포맷팅을 한번 진행해주세요
ktlint 라이브러리는 이 프로젝트에 있습니다.

2023-06-19 03:35 UTC, minseonglove commented on presentation/src/main/java/com/weit/presentation/ui/map/MapFragment.kt
> +    private var marker: Marker? = null
GoogleMap의 생명주기가 어떻게 돌아가는지 확인해본 다음 괜찮다면 Fragment의 View가 파괴될때 이녀석들도 해제해주세요

2023-06-19 03:35 UTC, minseonglove commented on presentation/src/main/java/com/weit/presentation/ui/map/MapFragment.kt
> +        }
xml에서 설정 가능한 요소들은 xml로 빼봅시다

2023-06-19 03:35 UTC, minseonglove commented on presentation/src/main/java/com/weit/presentation/ui/map/MapFragment.kt
> +    private var marker: Marker? = null
coordinates 같은 공유 변수를 두지 않고 구현할 수 있는 방법은 없을까요?

2023-06-19 03:35 UTC, minseonglove commented on presentation/src/main/java/com/weit/presentation/ui/map/PlacePredictionAdapter.kt
> +            }
apply로 감싸운 이유가 무어신가요

2023-06-19 03:35 UTC, minseonglove commented on presentation/src/main/java/com/weit/presentation/ui/map/MapFragment.kt
> +            }
여기서 리턴해주는 boolean의 역할은 무엇인가요?

2023-06-20 01:51 UTC, overthename commented on presentation/src/main/java/com/weit/presentation/ui/map/MapFragment.kt
> +    private var marker: Marker? = null
getMapAsync()를 사용하여 onMapReadyCallback을 등록합니다.  onMapReadyCallback를 등록하면 비동기로 googleMap객체를 얻을 수 있습니다.  googleMap객체가 준비되면 onMapReady( ) 함수가 자동으로 호출되는데 이 함수 매개변수에 좌표를 넣을 수 없어서 coordinates 공유변수를 두어야 할 것 같습니다.

2023-06-20 01:59 UTC, overthename commented on presentation/src/main/java/com/weit/presentation/ui/map/PlacePredictionAdapter.kt
> +            }
필요없는 것 같아서 뺐습니다..

2023-06-20 02:32 UTC, overthename commented on presentation/src/main/java/com/weit/presentation/ui/map/MapFragment.kt
> +            }
쿼리가 listener에 의해 처리된 경우 true, SearchView가 기본 작업을 수행하도록 하려면 false입니다. 근데 검색해보니onQueryTextSubmit에서는 키보드에 있는 '검색'돋보기 버튼을 선택하였을 때 일어나는데 return값이 false면 검색 키보드를 내리고 true이면 검색 키보드를 내리지 않는다고 합니당.. 
보통 toolbar에서 검색창을 구현하고 싶을 때 searchview를 쓰는거라 검색창은 추후에 다른 위젯으로 바뀔 수 있을 것 같습니다

2023-06-20 02:59 UTC, minseonglove approved these changes
죠습니다 ktlint도 잘 적용해줬군요
push할때마다 한번씩 돌려주면 좋아요

2023-06-20 02:59 UTC, minseonglove commented on presentation/src/main/java/com/weit/presentation/ui/map/MapFragment.kt
> +        mapFragment?.onDestroyView()
오 뭔가 onDestoyView가 있으면 onDestory도 있을거 같네요

2023-06-23 06:37 UTC, LeEjoNgmIn1 approved these changes
내가 늦게 봐서 못따라간것도 있는데 다음에는 리뷰수정 commit 올릴때는 그냥 리뷰 수정이라고만 올리지 말고 어떤 내용을 수정 했는지도 좀 적어줬으면 좋겠어 혼자 보면서 따라가는데 너무 어렵다 ㅠㅜ

2023-06-23 08:21 UTC, merged